name: FE Manual Build

on:
  workflow_dispatch:   # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Inject ENV from Secrets
      - name: Generate .env.production
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build FE
        run: pnpm build

      # Login ke GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      # Buat image tag
      - name: Set image name
        id: meta
        run: echo "IMAGE=ghcr.io/${{ secrets.CR_USERNAME }}/todo-app-fe:${{ github.sha }}" >> $GITHUB_OUTPUT

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ steps.meta.outputs.IMAGE }} .

      # Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ steps.meta.outputs.IMAGE }}

      - name: Done
        run: echo "Image pushed: ${{ steps.meta.outputs.IMAGE }}"
